services:
    composer:
        container_name: composer
        build:
            target: install
            dockerfile: ./.docker/php/Dockerfile
            context: .
        tty: true
        volumes:
            - ./source/website:/var/www
            - ~/.ssh:/root/.ssh
        networks:
            - local-network
    phpmyadmin:
        container_name: aciff-phpmyadmin
        image: phpmyadmin
        restart: always
        env_file:
            - .env
        networks:
            - local
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
            - "traefik.http.routers.phpmyadmin.tls=true"
            - "traefik.docker.network=traefik-proxy"
            - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.aciff.local`)"

networks:
    local-network:
        driver: bridge